#!/usr/bin/env bash
# Cassandra Control Agent – AxonOps-style install script
# Usage:
#   CASSANDRA_CONTROL_SERVER_URL=wss://your-server/agent sudo ./install-agent.sh
#   sudo ./install-agent.sh --server-url wss://your-server/agent
#
# Or from a one-liner (server hosts this script and you pass URL):
#   curl -sSL https://YOUR_SERVER/install-agent.sh | sudo bash -s -- --server-url wss://YOUR_SERVER/agent

set -e

INSTALL_DIR="${INSTALL_DIR:-/usr/share/cassandra-control}"
CONFIG_DIR="${CONFIG_DIR:-/etc/cassandra-control}"
BINARY_NAME="cassandra-control-agent"
CONFIG_FILE="$CONFIG_DIR/agent.yml"
SERVICE_USER="${SERVICE_USER:-cassandra-control}"
CASSANDRA_USER="${CASSANDRA_USER:-cassandra}"
CASSANDRA_GROUP="${CASSANDRA_GROUP:-cassandra}"

SERVER_URL=""
DOWNLOAD_BINARY=""
while [[ $# -gt 0 ]]; do
  case $1 in
    --server-url)
      SERVER_URL="$2"
      shift 2
      ;;
    --download-binary)
      DOWNLOAD_BINARY=1
      shift
      ;;
    *)
      shift
      ;;
  esac
done

if [[ -z "$SERVER_URL" ]]; then
  SERVER_URL="$CASSANDRA_CONTROL_SERVER_URL"
fi
if [[ -z "$SERVER_URL" ]]; then
  echo "Enter control server URL (e.g. wss://3.109.48.138/agent):"
  read -r SERVER_URL
  if [[ -z "$SERVER_URL" ]]; then
    echo "URL is required. Aborting."
    exit 1
  fi
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AGENT_SRC=""
if [[ -x "$SCRIPT_DIR/agent" ]]; then
  AGENT_SRC="$SCRIPT_DIR/agent"
elif [[ -x "$SCRIPT_DIR/$BINARY_NAME" ]]; then
  AGENT_SRC="$SCRIPT_DIR/$BINARY_NAME"
elif [[ -x "$SCRIPT_DIR/../../bin/agent" ]]; then
  AGENT_SRC="$SCRIPT_DIR/../../bin/agent"
fi

if [[ -n "$DOWNLOAD_BINARY" && -n "$SERVER_URL" ]]; then
  # Derive https URL from wss (e.g. wss://host/agent -> https://host/agent-binary)
  BINARY_BASE="${SERVER_URL#wss://}"
  BINARY_BASE="${BINARY_BASE#ws://}"
  BINARY_BASE="https://${BINARY_BASE%/agent}/agent-binary"
  echo "Downloading agent binary from $BINARY_BASE"
  TMP_AGENT=$(mktemp)
  if curl -sSLk -o "$TMP_AGENT" "$BINARY_BASE" && [[ -s "$TMP_AGENT" ]]; then
    chmod +x "$TMP_AGENT"
    AGENT_SRC="$TMP_AGENT"
  else
    echo "Warning: download failed; will try to use local binary if present."
    AGENT_SRC=""
  fi
fi

if [[ -z "$AGENT_SRC" || ! -x "$AGENT_SRC" ]]; then
  echo "Error: agent binary not found. Either:"
  echo "  1) Put the binary in $SCRIPT_DIR/agent or repo bin/agent, or"
  echo "  2) Use --download-binary and ensure the server serves the binary at /agent-binary"
  exit 1
fi

echo "Installing Cassandra Control Agent"
echo "  Server URL: $SERVER_URL"
echo "  Install dir: $INSTALL_DIR"
echo "  Config file: $CONFIG_FILE"
echo ""

# 1. Create directories
sudo mkdir -p "$INSTALL_DIR"
sudo mkdir -p "$CONFIG_DIR"

# 2. Copy binary
sudo cp "$AGENT_SRC" "$INSTALL_DIR/$BINARY_NAME"
sudo chmod +x "$INSTALL_DIR/$BINARY_NAME"

# 3. Create config file (AxonOps-style YAML)
sudo tee "$CONFIG_FILE" << EOF
# Cassandra Control Agent configuration
# Generated by install-agent.sh

server_url: "$SERVER_URL"
EOF
sudo chmod 0640 "$CONFIG_FILE"

# 4. Create user and set group membership
if ! getent group "$CASSANDRA_GROUP" > /dev/null 2>&1; then
  echo "Warning: group $CASSANDRA_GROUP not found. Skipping user/group setup."
  echo "  You may need to run the agent as root or adjust user/group manually."
  SERVICE_USER="root"
  CASSANDRA_GROUP="root"
fi
sudo useradd -r -s /bin/false "$SERVICE_USER" 2>/dev/null || true
sudo usermod -aG "$CASSANDRA_GROUP" "$SERVICE_USER" 2>/dev/null || true
if getent passwd "$CASSANDRA_USER" > /dev/null 2>&1; then
  sudo usermod -aG "$SERVICE_USER" "$CASSANDRA_USER" 2>/dev/null || true
fi

# 5. Ownership
sudo chown -R "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR"
sudo chown root:"$SERVICE_USER" "$CONFIG_FILE"

# 6. Systemd unit
sudo tee /etc/systemd/system/cassandra-control-agent.service << 'SVCEOF'
[Unit]
Description=Cassandra Control Agent
After=network.target

[Service]
Type=simple
User=cassandra-control
Group=cassandra-control
ExecStart=/usr/share/cassandra-control/cassandra-control-agent
Environment="CASSANDRA_CONTROL_AGENT_CONFIG=/etc/cassandra-control/agent.yml"
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
SVCEOF

# If we're not using cassandra-control user (e.g. group missing), override to root
if [[ "$SERVICE_USER" == "root" ]]; then
  sudo mkdir -p /etc/systemd/system/cassandra-control-agent.service.d
  sudo tee /etc/systemd/system/cassandra-control-agent.service.d/override.conf << 'EOF'
[Service]
User=root
Group=root
EOF
fi

sudo systemctl daemon-reload
sudo systemctl enable cassandra-control-agent
sudo systemctl start cassandra-control-agent

echo ""
echo "Cassandra Control Agent is installed and running."
echo "  Status: sudo systemctl status cassandra-control-agent"
echo "  Logs:   journalctl -u cassandra-control-agent -f"
echo "  Config: $CONFIG_FILE"
echo "In the control server dashboard, click 'Refresh nodes' to see this node."
