#!/usr/bin/env bash
# Cassandra Control Agent – install from GitHub (AxonOps-style)
#
# One-line install (replace YOUR_GITHUB_ORG, YOUR_REPO, and YOUR_SERVER):
#   curl -sSL https://raw.githubusercontent.com/YOUR_GITHUB_ORG/YOUR_REPO/main/scripts/install-agent.sh | sudo bash -s -- --server-url wss://YOUR_SERVER/agent
#
# With default GitHub repo (set GITHUB_REPO or use --github-repo):
#   curl -sSL https://raw.githubusercontent.com/YOUR_ORG/cassandra-control/main/scripts/install-agent.sh | sudo bash -s -- --server-url wss://YOUR_SERVER/agent
#
# Options:
#   --server-url URL    (required) Control server WebSocket URL, e.g. wss://control.example.com/agent
#   --github-repo REPO  GitHub repo for downloads, e.g. myorg/cassandra-control (default: from script or env GITHUB_REPO)
#   --version VERSION   Release version, e.g. v0.1.0 (default: latest)

set -e

INSTALL_DIR="${INSTALL_DIR:-/usr/share/cassandra-control}"
CONFIG_DIR="${CONFIG_DIR:-/etc/cassandra-control}"
BINARY_NAME="cassandra-control-agent"
CONFIG_FILE="$CONFIG_DIR/agent.yml"
SERVICE_USER="${SERVICE_USER:-cassandra-control}"
CASSANDRA_USER="${CASSANDRA_USER:-cassandra}"
CASSANDRA_GROUP="${CASSANDRA_GROUP:-cassandra}"
# Default repo when installed from GitHub
GITHUB_REPO="${GITHUB_REPO:-Suhel0328/cassandra-control}"
VERSION="${VERSION:-latest}"

SERVER_URL=""
while [[ $# -gt 0 ]]; do
  case $1 in
    --server-url)
      SERVER_URL="$2"
      shift 2
      ;;
    --github-repo)
      GITHUB_REPO="$2"
      shift 2
      ;;
    --version)
      VERSION="$2"
      shift 2
      ;;
    *)
      shift
      ;;
  esac
done

if [[ -z "$SERVER_URL" ]]; then
  SERVER_URL="$CASSANDRA_CONTROL_SERVER_URL"
fi
if [[ -z "$SERVER_URL" ]]; then
  echo "Enter control server URL (e.g. wss://control.example.com/agent):"
  read -r SERVER_URL
  if [[ -z "$SERVER_URL" ]]; then
    echo "Error: server URL is required. Use --server-url wss://YOUR_SERVER/agent"
    exit 1
  fi
fi

# Detect arch for GitHub download
ARCH=$(uname -m)
case "$ARCH" in
  x86_64)  ARCH="amd64" ;;
  aarch64|arm64) ARCH="arm64" ;;
  *)       ARCH="$ARCH" ;;
esac
OS=$(uname -s)
case "$OS" in
  Linux)   OS="linux" ;;
  *)       OS="$OS" ;;
esac

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" 2>/dev/null && pwd)"
AGENT_SRC=""

# 1) Local binary (when run from cloned repo)
if [[ -n "$SCRIPT_DIR" ]]; then
  for candidate in "$SCRIPT_DIR/agent" "$SCRIPT_DIR/$BINARY_NAME" "$SCRIPT_DIR/../bin/agent"; do
    if [[ -x "$candidate" ]]; then
      AGENT_SRC="$candidate"
      break
    fi
  done
fi

# 2) Download from GitHub Releases if no local binary
if [[ -z "$AGENT_SRC" ]]; then
  if [[ "$VERSION" == "latest" ]]; then
    echo "Fetching latest release from GitHub..."
    VERSION=$(curl -sS "https://api.github.com/repos/${GITHUB_REPO}/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
    [[ -z "$VERSION" ]] && { echo "Error: could not get latest release from ${GITHUB_REPO}"; exit 1; }
    echo "  Version: $VERSION"
  fi
  DOWNLOAD_URL="https://github.com/${GITHUB_REPO}/releases/download/${VERSION}/cassandra-control-agent-${OS}-${ARCH}"
  echo "Downloading agent from $DOWNLOAD_URL"
  TMP_AGENT=$(mktemp)
  if ! curl -sSL -o "$TMP_AGENT" "$DOWNLOAD_URL"; then
    echo "Error: download failed. Check GITHUB_REPO ($GITHUB_REPO), VERSION ($VERSION), and that the release asset exists."
    echo "  Expected asset name: cassandra-control-agent-${OS}-${ARCH}"
    rm -f "$TMP_AGENT"
    exit 1
  fi
  [[ -s "$TMP_AGENT" ]] || { echo "Error: downloaded file is empty"; rm -f "$TMP_AGENT"; exit 1; }
  chmod +x "$TMP_AGENT"
  AGENT_SRC="$TMP_AGENT"
fi

echo "Installing Cassandra Control Agent"
echo "  Server URL: $SERVER_URL"
echo "  Install dir: $INSTALL_DIR"
echo "  Config file: $CONFIG_FILE"
echo ""

sudo mkdir -p "$INSTALL_DIR"
sudo mkdir -p "$CONFIG_DIR"
sudo cp "$AGENT_SRC" "$INSTALL_DIR/$BINARY_NAME"
sudo chmod +x "$INSTALL_DIR/$BINARY_NAME"
[[ "$AGENT_SRC" == /tmp/* ]] && rm -f "$AGENT_SRC"

sudo tee "$CONFIG_FILE" << EOF
# Cassandra Control Agent configuration
# Generated by install-agent.sh – edit server_url if needed

server_url: "$SERVER_URL"
EOF
sudo chmod 0640 "$CONFIG_FILE"

if ! getent group "$CASSANDRA_GROUP" > /dev/null 2>&1; then
  echo "Warning: group $CASSANDRA_GROUP not found. Running agent as root."
  SERVICE_USER="root"
  CASSANDRA_GROUP="root"
fi
sudo useradd -r -s /bin/false "$SERVICE_USER" 2>/dev/null || true
sudo usermod -aG "$CASSANDRA_GROUP" "$SERVICE_USER" 2>/dev/null || true
if getent passwd "$CASSANDRA_USER" > /dev/null 2>&1; then
  sudo usermod -aG "$SERVICE_USER" "$CASSANDRA_USER" 2>/dev/null || true
fi

sudo chown -R "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR"
sudo chown root:"$SERVICE_USER" "$CONFIG_FILE"

sudo tee /etc/systemd/system/cassandra-control-agent.service << 'SVCEOF'
[Unit]
Description=Cassandra Control Agent
After=network.target

[Service]
Type=simple
User=cassandra-control
Group=cassandra-control
ExecStart=/usr/share/cassandra-control/cassandra-control-agent
Environment="CASSANDRA_CONTROL_AGENT_CONFIG=/etc/cassandra-control/agent.yml"
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
SVCEOF

if [[ "$SERVICE_USER" == "root" ]]; then
  sudo mkdir -p /etc/systemd/system/cassandra-control-agent.service.d
  sudo tee /etc/systemd/system/cassandra-control-agent.service.d/override.conf << 'EOF'
[Service]
User=root
Group=root
EOF
fi

sudo systemctl daemon-reload
sudo systemctl enable cassandra-control-agent
sudo systemctl start cassandra-control-agent

echo ""
echo "Cassandra Control Agent is installed and running."
echo "  Status: sudo systemctl status cassandra-control-agent"
echo "  Config: $CONFIG_FILE"
echo "In the control server dashboard, click 'Refresh nodes' to see this node."
